apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-first-nginx-rs
  labels:
    app: my-first-nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        app: my-first-nginx
        tier: frontend
    spec:
      containers:
      - name: my-first-nginx
        image: stacksimplify/kubenginx:1.0.0